### ISSUE TITLE
안녕하세요 블로그에 퍼가도 될까요?

### ISSUE THREAD

**Issue by Kyun2da** [denlyou/study_markdown_github#1]
안녕하세요 문서가 너무 유용하여 포스팅하고 싶은데
이 문서를 블로그에 퍼가도 될까요?
문제있을시 삭제하겠습니다.
kyun2dot@gmail.com 으로 연락주시면 바로 삭제할게요..!
블로그 주소는 https://kyun2da.github.io 입니다!!

**Comment by denlyou** [comment]
#1 네! 자유롭게 사용하셔도 됩니다~
